packages:
  - 'svelte-maplibre-gl'
  - 'extensions/*'
  - '.'

catalog:
  # Core dependencies
  'maplibre-gl': '^5.6.0'
  'svelte': '^5.33.14'

  # Extension dependencies
  '@deck.gl/core': '^9.1.12'
  '@deck.gl/layers': '^9.1.12'
  '@deck.gl/mapbox': '^9.1.12'
  'maplibre-contour': '^0.1.0'
  'pmtiles': '^4.3.0'
  'terra-draw': '^1.0.0'
  'terra-draw-maplibre-gl-adapter': '^1.0.3'

  # Build tools
  '@sveltejs/kit': '^2.22.2'
  '@sveltejs/package': '^2.3.12'
  '@sveltejs/vite-plugin-svelte': '^5.1.0'
  'publint': '^0.3.12'
  'svelte-check': '^4.2.1'
  'typescript': '^5.8.3'
  'vite': '^7.0.2'

  # Types
  '@types/geojson': '^7946.0.16'
