packages:
  - svelte-maplibre-gl
  - extensions/*
  - .

catalog:
  '@deck.gl/core': ^9.2.5
  '@deck.gl/layers': ^9.2.5
  '@deck.gl/mapbox': ^9.2.5
  '@sveltejs/kit': ^2.49.2
  '@sveltejs/package': ^2.5.7
  '@sveltejs/vite-plugin-svelte': ^6.2.1
  '@types/geojson': ^7946.0.16
  maplibre-contour: ^0.1.0
  maplibre-gl: ^5.15.0
  pmtiles: ^4.3.2
  publint: ^0.3.16
  svelte: 5.39.7
  svelte-check: ^4.3.5
  terra-draw: ^1.21.2
  terra-draw-maplibre-gl-adapter: ^1.2.3
  typescript: ^5.9.3
  vite: ^6.4.1
