packages:
  - 'svelte-maplibre-gl'
  - 'extensions/*'
  - '.'

catalog:
  # Core dependencies
  'maplibre-gl': '^5.6.2'
  'svelte': '^5.35.4'

  # Extension dependencies
  '@deck.gl/core': '^9.1.14'
  '@deck.gl/layers': '^9.1.14'
  '@deck.gl/mapbox': '^9.1.14'
  'maplibre-contour': '^0.1.0'
  'pmtiles': '^4.3.0'
  'terra-draw': '^1.0.0'
  'terra-draw-maplibre-gl-adapter': '^1.0.3'

  # Build tools
  '@sveltejs/kit': '^2.27.1'
  '@sveltejs/package': '^2.4.0'
  '@sveltejs/vite-plugin-svelte': '^6.1.0'
  'publint': '^0.3.12'
  'svelte-check': '^4.3.1'
  'typescript': '^5.9.2'
  'vite': '^6.0.0'

  # Types
  '@types/geojson': '^7946.0.16'
