packages:
  - svelte-maplibre-gl
  - extensions/*
  - .

catalog:
  '@deck.gl/core': ^9.2.6
  '@deck.gl/layers': ^9.2.6
  '@deck.gl/mapbox': ^9.2.6
  '@sveltejs/kit': ^2.50.1
  '@sveltejs/package': ^2.5.7
  '@sveltejs/vite-plugin-svelte': ^6.2.4
  '@types/geojson': ^7946.0.16
  maplibre-contour: ^0.1.0
  maplibre-gl: 5.17.0
  pmtiles: ^4.3.2
  publint: ^0.3.17
  svelte: ^5.48.5
  svelte-check: ^4.3.5
  terra-draw: ^1.23.1
  terra-draw-maplibre-gl-adapter: ^1.2.3
  typescript: ^5.9.3
  vite: ^7.3.1

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
